import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"; // Ensure this is the correct import
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MYCONF Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Use the metadata object for favicon and other head elements */}
      <head>
        <link rel="shortcut icon" href="/favicon.png" />
      </head>
      <body className={inter.className}>
        {/* Wrap everything with AuthProvider */}
        <AuthProvider>
          <StoreProvider>
              {children}
              <Toaster /> {/* Render the Toaster component */}
            </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}